### ISSUE TITLE
Versions 1.2.0 and 1.3.0 need git tags

### ISSUE THREAD

**Issue by olgeni** [blt/port_compiler#29]
Helpful reminder :)

**Comment by tsloughter** [comment]
Just looked and realized I haven't been tagging releases, instead just bumping the version and publishing.

**Comment by ghost** [comment]
Does that mean you're going to push the missing tags? If not, I can do it as well.

**Comment by olgeni** [comment]
(ping)

**Comment by ghost** [comment]
@tsloughter, can you add the missing tags?

**Comment by ghost** [comment]
(ping)

**Comment by ghost** [comment]
@tsloughter, unless you think we shouldn't push the missing tags, I intend to create the following releases:

v1.2.0 https://github.com/blt/port_compiler/commit/63247e8090115223982925079e76e6d491ad1169
v1.3.0 https://github.com/blt/port_compiler/commit/9df79cd4409489ca9f1e8e6aeb2f74c272695ce3
v1.4.0 https://github.com/blt/port_compiler/commit/53c412cafbb1e0bba87cf617ce736d831d8f4dcc
v1.5.0 https://github.com/blt/port_compiler/commit/c2f3fb1c5088433a680369633e39287bac53f5c1

**Comment by ghost** [comment]
Created tags as planned.

**Comment by ghost** [comment]
@tsloughter, @ferd, same issue with the 1.6.0 release. Can you please tag `v1.6.0`?

**Comment by djnym** [comment]
@tuncer I think there is a tag, but it's 1.6.0, not v1.6.0, so this can probably be closed again.

**Comment by ghost** [comment]
You're right, though all tags since 1.0.0 are of the form `vX.Y.Z`, and that makes more sense because you can easily differentiate between a versioned branch and tags. Also, since it's been consistent from 1.0.0 up till 1.5.0, I'd suggest to tag `v1.6.0` and stick with it. Not sure if the unexpected, prefix-less `1.6.0` can be safely removed in that case.

@tsloughter, do you intend to switch to no-prefix tags? If you do, you might want to create the missing no-prefix tags for 1.0.0 - 1.5.0 first.

**Comment by tsloughter** [comment]
I really don't care. I don't know why it matters, tags are just for development.

**Comment by ghost** [comment]
Tags are needed to reference releases, independent of how development is done. Given that you cut the releases, it's easiest if you to create the tags at the same time. Otherwise, one of the other contributors has to catch a release, find the commit, create and push a tag. I don't think that's a sustainable way to maintain tagged releases.

**Comment by ghost** [comment]
Regardless of how the tags are maintained, assuming we want tags, can we please conclude the tag naming scheme inconsistency issue (https://github.com/blt/port_compiler/issues/29#issuecomment-304378721)?

**Comment by ghost** [comment]
ping?

**Comment by ghost** [comment]
Tagged v1.6.0.
