### ISSUE TITLE
REBAR_DEPS_DIR doesn't get expanded

### ISSUE THREAD

**Issue by asabil** [blt/port_compiler#30]
I tried porting https://github.com/tonyrog/bt/blob/master/rebar.config to rebar3+pc but the build fails due to $REBAR_DEPS_DIR not being expanded.

**Comment by kape1395** [comment]
I have the same problem.
Would you accept a pull request, if I would prepare it?
Or should I solve it in some other way?

**Comment by cjkjellander** [comment]
We are being hit by this too.

When using `{port_env, [{"CFLAGS", "$CFLAGS -I$REBAR_DEPS_DIR"}]}.`

```===> /home/cjk/git/campanja/csv/c_src/csv_parser_nif.c:5:24: fatal error: libcsv/csv.h: No such file or directory```

So no expansion.

**Comment by cjkjellander** [comment]
I've checked the rebar3 code a bit. Rebar3 only sets the env for hooks, but not at all for provider hooks. Also, there is no env in `#state_t{}`, which it would need to do variable expansion in the port_spec, since this is inside erlang, and not running external commands.

For example:
`{port_specs, [{"priv/csv_parser_nif.so",
               ["c_src/csv_parser_nif.c",
                "$REBAR_DEPS_DIR/libcsv/libcsv.c"]}]}.`

The $REBAR_DEPS_DIR will not be expanded in this case.

**Comment by cjkjellander** [comment]
So, there is a fix for this issue in https://github.com/blt/port_compiler/pull/38

Please try it out.
