### ISSUE TITLE
compile_commands.json left in root of project

### ISSUE THREAD

**Issue by djnym** [blt/port_compiler#34]
Would it be possible to drop it under _build somewhere?

**Comment by tsloughter** [comment]
Yea, what is this?

**Comment by tsloughter** [comment]
Looks like @tuncer added it.

I guess I can make it so it is something someone can turn on instead of just completely removing it... no reason to be on by default for sure.

**Comment by ghost** [comment]
It's needed for `clang-tidy` etc. to work. 

https://clang.llvm.org/docs/JSONCompilationDatabase.html
https://clang.llvm.org/docs/HowToSetupToolingForLLVM.html

Instead of making it opt-in, we could make it opt-out, but the best solution is to start the file with a JSON comment describing what it's for and why it's in this place. I wish CC/CXX tooling had more predictable paths, but there's no conventional path for `clang-*` to search for this file. This doesn't require sources to be built by clang, so it cannot assume clang built and created, say, `_build/compile_commands.json`.

**Comment by tsloughter** [comment]
It should definitely stay opt-in. It isn't needed and is confusing.

**Comment by ghost** [comment]
Looks like there's no way to add comments in JSON files.

**Comment by tsloughter** [comment]
Correct. JSON is a horrible format to use for files like this.

And it could be the default and require an opt-out if it was only created in the case that clang is used.

**Comment by ghost** [comment]
It also works if you build with gcc and, to be clear, gcc doesn't know anything about clang. The primary need is for things like include paths and such to be known when trying to process C/C++.

**Comment by tsloughter** [comment]
Ah, ok, if it isn't specific to a compiler then it can remain as a global opt-in.

**Comment by ghost** [comment]
I wouldn't change the default now, since it's not a new change in a recent release.

**Comment by tsloughter** [comment]
We already did and published 1.6.0, it was a mistake to make it the default in the first place and my fault for not catching it earlier.

Was this brought up as something to add in an issue in rebar2 or something? Meaning it is being used by someone we could reach out to?

**Comment by ghost** [comment]
Limiting writing of compile_commands.json to the case of CC=clang could make sense, but it's not that simple to check. cc/c++ can be clang when it's the default host CC.

Hypothetically, say you ran `clang-tidy` and compile_commands.json for some reason (unusual commands) tripped up `clang-tidy`. How likely is this, and would it warrant complicating port_compiler to conditionalize this on CC=clang/CXX=clang++? Remember that CC=cc and CXX=c++ by default and this does use gcc or clang depending on the environment. You'd have to try parsing the version string to be certain.

**Comment by ghost** [comment]
It was added to rebar2 and port_compiler to support newer clang tools. IIRC, I fixed this before anyone reported it, since noticing required a newer clang toolchain.

If it's generally considered to be a nuisance, feel free to make it opt-in. That would require appropriate communication for users to learn of the opt-in rebar.config flag.

**Comment by ghost** [comment]
Maybe instead of opt-in it actually is a good idea to detect clang and use that as the condition. However, it's easy to find online discussions about using gcc and compile_commands.json, so my previous comments regarding over-complicating the check coupled with the possibility of CC=gcc compile_commands.json outweigh a flag-free condition. Do you agree?

**Comment by tsloughter** [comment]
I agree, leaving it as opt-in.

**Comment by ghost** [comment]
FYI, CMake also supports this.

**Comment by ghost** [comment]
Since I forward-ported rebar2's port_compiler to blt/port_compiler, they're synced. If you think the behavior should stay synchronized in both copies of the plugin, feel free to push the diff there (including `rebar.config.sample`) as well.

**Comment by djnym** [comment]
So I don't know what the clang-* tools are but I found clang-tidy and it appears to support a --config command line option, is there any reason which we can't just try to get ```clang-tidy --config _build/compile_commands.json``` to work?  It might require changing the paths in the file, but the docs @tuncer pointed to seem to have the concept of a build directory versus a source directory.

**Comment by ghost** [comment]
@djnym, I didn't catch it at first, but apparently port_compiler v2.6.0 was already released and turned the feature into an opt-in flag, so we've been discussing an issue that has been fixed. That change removes the confusion which sparked this ticket. But most importantly requiring users to pass `--config` in addition to enable the new flag, coupled with implementation questions to resolve like, say, the stability of the new location and figuring out the new paths in the JSON term are enough reasons to not bother with that, if you ask me. I don't think we would gain anything by attempting that, and it's basically the same situation as with `ct_log_dir` or `cover_export_enabled`. Therefore, unless you disagree, I think this ticket has been resolved in v2.6.0 already.

**Comment by djnym** [comment]
I see, it looks like it's actually tagged 1.6.0, and does seem to make it opt-in, so this is fine with me.

**Comment by ghost** [comment]
Sorry, I meant 1.6.0 but wrote 2.6.0.
